CREATE TABLE IF NOT EXISTS sujets (
    id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    numbdbac SMALLINT,
    annee SMALLINT,
    serie VARCHAR(6),
    lieu TEXT,
    session TEXT,
    code VARCHAR(11),
    rang SMALLINT,
    sujet TEXT,
    notions TEXT,
    auteur VARCHAR(30),
    PRIMARY KEY (id)
);
