name: Installation du projet
on : push
jobs:
  mon_job:
    name: build de l'application
    runs-on: ubuntu-latest
    steps:
      - name: Récupération de notre application
        uses: actions/checkout@v6
      - name: Installation des dépendances
        run: npm ci
      - name: build de l'application
        run: npm run build
      - name: test
        run: npm run test