name: pull request
on:
  pull_request:
    types: 
      - opened # C'est le type par défaut

jobs:
  exemple:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Il y a eu une pull request..."

    