name: Demo matrix
on:
  - push

jobs:
  test_matrix:
    name: Test node  ${{ matrix.node-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: false permet de continuer les autres tests même si un échoue
      fail-fast: false
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Récupération de notre application
        uses: actions/checkout@v6

      - name: Configuration node ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Installation des dépendances
        run: npm ci
      - name: build de l'application
        run: npm run build
      - name: test
        run: npm run test