FROM python:3.11.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY train_ml.py .

RUN mkdir -p /app/models /app/logs

ENTRYPOINT ["python", "train_ml.py"]