# Nom pour le workflow
name: Premier workflow
# On précise quel est le déclencheur de notre workflow
on: 
  - workflow_dispatch
  - push
# On précise les actions à réaliser lors du déclenchement de ce workflow
jobs:
  # Définition de la première action à réaliser
  premier-job:
    name: premier job
    # On précise le système d'exploitation
    runs-on: ubuntu-latest
    # On écrit ici les étapes pour notre action
    steps:
      # On donne un nom à notre étape & une commande à effectuer
      - name: Dit bonjour
        run: echo 'Hello world !'
      - name: Dit au revoir
        run: echo "Goodbye"

  second-job:
    # Ce job dépend ici du premier
    needs: premier-job
    name: Mon second job
    runs-on: ubuntu-latest
    steps:
      - name: Mon étape
        run: echo "Je suis un second job"